Fix/clicking on a memory should open it in a new tab (#167)
supermemoryai/supermemory pull request #169
Opened 2024-07-26 07:03 UTC by dishit7

This PR addresses the issue of external links opening in the same tab. I've added target="_blank" rel="noopener noreferrer" to the Link component for external sources. Due to setup limitations, I wasn't able to fully test this change. I would appreciate review and testing assistance from the maintainers or other contributors.

2024-07-26 14:43 UTC, Dhravya requested changes
Thanks for the PR! Really appreciate it.

bring back wrangler.toml files, that's it :)

2024-07-26 14:43 UTC, Dhravya commented on apps/cf-ai-backend/.gitignore
Wrangler.toml files are not supposed to be in gitignore! it's public information and still safe. however, the contributors shouldn't push their wrangler.toml files so that the deployment doesn't break

2024-07-26 14:43 UTC, Dhravya commented on apps/cf-ai-backend/wrangler.toml
(that would bring this back)

2024-07-26 14:43 UTC, Dhravya commented on apps/web/server/auth.ts
Revert this too pls!

2024-07-26 14:43 UTC, Dhravya commented on package.json
nice. thanks for this

2024-07-26 17:21 UTC, dishit7 commented on apps/web/server/auth.ts
If I fix the wrangler.toml issue and make a commit that should fix this as well right cause I think the change is due to some blank space otherwise the file is unchanged.

2024-07-28 00:12 UTC, CodeTorso commented
I believe this is fixed

2024-07-28 00:12 UTC, closed without merging